# Generated by Django 5.2.6 on 2025-10-08 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_nftstatistics_userstatistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='current bid'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_auctions', to=settings.AUTH_USER_MODEL, verbose_name='highest bidder'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='nft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='nft.nft', verbose_name='nft'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='reserve price'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL, verbose_name='seller'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='start price'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='nft.auction', verbose_name='auction'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='bidder'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner_image',
            field=models.URLField(blank=True, verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='featured_image',
            field=models.URLField(blank=True, verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='floor_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='floor price'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='nfts',
            field=models.ManyToManyField(blank=True, related_name='collections', to='nft.nft', verbose_name='nfts'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='total volume'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nft.nft', verbose_name='nft'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='favoritecollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='nft.collection', verbose_name='collection'),
        ),
        migrations.AlterField(
            model_name='favoritecollection',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='favoritecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_collections', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft.nft', verbose_name='nft'),
        ),
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='attributes',
            field=models.JSONField(default=dict, verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='blockchain',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Polygon', 'Polygon'), ('Solana', 'Solana'), ('Binance', 'Binance Smart Chain')], default='Ethereum', max_length=20, verbose_name='blockchain'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nft.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='contract_address',
            field=models.CharField(max_length=42, verbose_name='contract address'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_nfts', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='currency',
            field=models.CharField(default='ETH', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='external url'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='is_listed',
            field=models.BooleanField(default=False, verbose_name='is_listed'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_nfts', through='nft.Like', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='metadata_url',
            field=models.URLField(blank=True, verbose_name='metadata url'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='minted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='minted at'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='previous_owners',
            field=models.ManyToManyField(related_name='previously_owned_nfts', through='nft.OwnershipHistory', to=settings.AUTH_USER_MODEL, verbose_name='previous owners'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='rarity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='rarity_score'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='status',
            field=models.CharField(choices=[('minted', 'Minted'), ('listed', 'Listed for Sale'), ('auction', 'On Auction'), ('sold', 'Sold'), ('burned', 'Burned')], default='minted', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='tags',
            field=models.ManyToManyField(blank=True, to='nft.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Token id'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token_standard',
            field=models.CharField(choices=[('ERC-721', 'ERC-721'), ('ERC-1155', 'ERC-1155'), ('SPL', 'SPL')], default='ERC-721', max_length=10, verbose_name='token_standard'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='nftstatistics',
            name='average_sale_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='average sale price'),
        ),
        migrations.AlterField(
            model_name='nftstatistics',
            name='last_sale_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='last_sale price'),
        ),
        migrations.AlterField(
            model_name='nftstatistics',
            name='nft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='nft.nft', verbose_name='nft'),
        ),
        migrations.AlterField(
            model_name='nftstatistics',
            name='total_comments',
            field=models.PositiveIntegerField(default=0, verbose_name='total comments'),
        ),
        migrations.AlterField(
            model_name='nftstatistics',
            name='total_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='total likes'),
        ),
        migrations.AlterField(
            model_name='nftstatistics',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='total views'),
        ),
        migrations.AlterField(
            model_name='nftstatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(default='ETH', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires at'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='nft.nft', verbose_name='nft'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft.nft', verbose_name='nft'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='transaction_hash',
            field=models.CharField(max_length=66, verbose_name='transaction_hash'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='total_collections',
            field=models.PositiveIntegerField(default=0, verbose_name='total collections'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='total_nfts_created',
            field=models.PositiveIntegerField(default=0, verbose_name='total nfts created'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='total_nfts_owned',
            field=models.PositiveIntegerField(default=0, verbose_name='total nfts owned'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='total_sales',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='total sales'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='total_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='total volume'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
