# Generated by Django 5.2.6 on 2025-11-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_alter_auction_active_alter_auction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='nft_images/', verbose_name='image file'),
        ),
    ]
